spring:
  main:
    allow-bean-definition-overriding: true
  jmx:
    enabled: false
  application:
    name: Demo

server:
  port: 8062
  error:
    include-stacktrace: never

kafka:
  broker:
    host: ${KAFKA_BROKER_HOST:localhost}
    port: ${KAFKA_BROKER_PORT:19092}
  schema:
    host: ${SCHEMA_BROKER_HOST:localhost}
    port: ${SCHEMA_BROKER_PORT:9090}
  group:
    default: blue-origin-anomaly
  topics:
    anomaly: teamj.anomaly.0
    telemetryrocket: teamj.telemetry-rocket.0
    telemetrybooster: teamj.telemetry-booster.0
    telemetrypayload: teamj.telemetry-payload.0
