spring:
  main:
    allow-bean-definition-overriding: true
  jmx:
    enabled: false
  application:
    name: Demo

server:
  port: 8050
  error:
    include-stacktrace: never

kafka:
  broker:
    host: ${KAFKA_BROKER_HOST:localhost}
    port: ${KAFKA_BROKER_PORT:19092}
  schema:
    host: ${SCHEMA_BROKER_HOST:localhost}
    port: ${SCHEMA_BROKER_PORT:9090}
  group:
    default: blue-origin-payload
  topics:
    rocketstatus: teamj.rocket-status.0
    payloadstatus: teamj.payload-status.0
    newpayload: teamj.new-payload.0
