spring:
  main:
    allow-bean-definition-overriding: true
  jmx:
    enabled: false
  application:
    name: Demo

server:
  port: 8050
  error: 
    include-stacktrace: never

grpc:
  enable-reflection: true
  port: 8051
