version: "3.0"
services:
  # BLUE ORIGIN
  weather:
    build: ./team-j-weather-ws
    container_name: team-j-blue-galactic-weather
    mem_limit: 160m
    ports:
      - "8060:8060"

  rocket:
    build: ./team-j-rocket-ws
    container_name: team-j-blue-galactic-rocket
    mem_limit: 160m
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - mission-preparation
      - booster
      - broker

  mission-preparation:
    build: ./team-j-mission-preparation-ws
    container_name: team-j-blue-galactic-mission-preparation
    mem_limit: 160m
    ports:
      - "8070:8070"
    depends_on:
      - broker

  database:
    image: mongo:latest
    volumes:
      - ./database:/data
    container_name: team-j-blue-galactic-database
    ports:
      - 27017:27017

  telemetry-writer:
    build: ./team-j-telemetry-writer-ws
    mem_limit: 160m
    container_name: team-j-blue-galactic-telemetry-writer
    ports:
      - "8092:8092"
    links:
      - database
    depends_on:
      - broker

  telemetry-reader:
    build: ./team-j-telemetry-reader-ws
    mem_limit: 160m
    container_name: team-j-blue-galactic-telemetry-reader
    ports:
      - "8094:8094"
    links:
      - database

  payload:
    build: ./team-j-payload-ws
    mem_limit: 160m
    container_name: team-j-blue-galactic-payload
    ports:
      - "8050:8050"
    depends_on:
      - broker

  booster:
    build: ./team-j-booster-ws
    mem_limit: 160m
    container_name: team-j-blue-galactic-booster
    ports:
      - "8030:8030"
      - "8031:8031"
    depends_on:
      - broker

  missionlogwriter:
    build: ./team-j-missionlogwriter-ws
    mem_limit: 160m
    container_name: team-j-blue-galactic-missionlogwriter
    ports:
      - "8010:8010"
    depends_on:
      - broker
    links:
      - database

  missionlogreader:
    build: ./team-j-missionlogreader-ws
    mem_limit: 160m
    container_name: team-j-blue-galactic-missionlogreader
    ports:
      - "8110:8110"
    depends_on:
      - broker
    links:
      - database
  mission-control:
    build: ./team-j-mission-control-ws
    mem_limit: 160m
    container_name: team-j-blue-galactic-mission-control
    ports:
      - "8200:8200"
    depends_on:
      - broker
      
  # KAFKA
  zookeeper:
    image: confluentinc/cp-zookeeper:6.0.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "9091:9091"
    environment:
      ZOOKEEPER_CLIENT_PORT: 9091
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:6.0.0
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "19092:19092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:9091"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,CONNECTIONS_FROM_HOST://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONNECTIONS_FROM_HOST:PLAINTEXT
      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:9090
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"

  schema-registry:
    image: confluentinc/cp-schema-registry:6.0.0
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - broker
    ports:
      - "9090:9090"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "zookeeper:9091"
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "broker:9092"
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:9090

  kafka-setup:
    image: confluentinc/cp-kafka:6.0.0
    hostname: setup
    container_name: setup
    depends_on:
      - broker
      - schema-registry
    command: "bash -c 'echo Waiting for Kafka to be ready... && \
      cub kafka-ready -b broker:9092 1 240 && \
      kafka-topics --create --if-not-exists --zookeeper zookeeper:9091 --partitions 1 --replication-factor 1 --topic teamj.sample.0 \
      && \
      kafka-topics --create --if-not-exists --zookeeper zookeeper:9091 --partitions 1 --replication-factor 1 --topic teamj.rocket-status.0 \
      && \
      kafka-topics --create --if-not-exists --zookeeper zookeeper:9091 --partitions 1 --replication-factor 1 --topic teamj.payload-status.0 \
      && \
      kafka-topics --create --if-not-exists --zookeeper zookeeper:9091 --partitions 1 --replication-factor 1 --topic teamj.booster-status.0 \
      && \
      kafka-topics --create --if-not-exists --zookeeper zookeeper:9091 --partitions 1 --replication-factor 1 --topic teamj.department-status.0 \
      && \
      kafka-topics --create --if-not-exists --zookeeper zookeeper:9091 --partitions 1 --replication-factor 1 --topic teamj.telemetry-booster.0 \
      && \
      kafka-topics --create --if-not-exists --zookeeper zookeeper:9091 --partitions 1 --replication-factor 1 --topic teamj.telemetry-rocket.0 \
      && \
      kafka-topics --create --if-not-exists --zookeeper zookeeper:9091 --partitions 1 --replication-factor 1 --topic teamj.telemetry-payload.0 \
      && \
      kafka-topics --create --if-not-exists --zookeeper zookeeper:9091 --partitions 1 --replication-factor 1 --topic teamj.mission-preparation.0 \
      && \
      kafka-topics --create --if-not-exists --zookeeper zookeeper:9091 --partitions 1 --replication-factor 1 --topic teamj.new-payload.0 \
      '"
    environment:
      KAFKA_BROKER_ID: ignored
      KAFKA_ZOOKEEPER_CONNECT: ignored
