spring:
  main:
    allow-bean-definition-overriding: true
  jmx:
    enabled: false
  application:
    name: Demo

server:
  port: 8080
  error:
    include-stacktrace: never

grpc:
  enable-reflection: true
  port: 8081

api:
  telemetry:
    host: ${TELEMETRY_HOST:localhost}
    port: ${TELEMETRY_PORT:8090}
  mission:
    host: ${MISSION_HOST:localhost}
    port: ${MISSION_PORT:8070}
    grpc: ${MISSION_GRPC:8071}
  booster:
    host: ${BOOSTER_HOST:localhost}
    port: ${BOOSTER_PORT:8030}
    grpc: ${BOOSTER_GRPC:8031}

kafka:
  broker:
    host: ${KAFKA_BROKER_HOST:localhost}
    port: ${KAFKA_BROKER_PORT:19092}
  schema:
    host: ${SCHEMA_BROKER_HOST:localhost}
    port: ${SCHEMA_BROKER_PORT:9090}
  group:
    default: blue-origin-rocket
  topics:
    rocketstatus: teamj.rocket-status.0
    departmentstatus: teamj.department-status.0
