spring:
  main:
    allow-bean-definition-overriding: true
  jmx:
    enabled: false
  application:
    name: Demo

server:
  port: 8080
  error:
    include-stacktrace: never

grpc:
  enable-reflection: true
  port: 8081

api:
  telemetry:
    host: ${TELEMETRY_HOST:localhost}
    port: ${TELEMETRY_PORT:8090}
  mission:
    host: ${MISSION_HOST:localhost}
    port: ${MISSION_PORT:8070}
