spring:
  main:
    allow-bean-definition-overriding: true
  jmx:
    enabled: false
  application:
    name: Demo

server:
  port: 8070

kafka:
  broker:
    host: ${KAFKA_BROKER_HOST:localhost}
    port: ${KAFKA_BROKER_PORT:19092}
  schema:
    host: ${SCHEMA_BROKER_HOST:localhost}
    port: ${SCHEMA_BROKER_PORT:9090}
  group:
    default: blue-origin-mission
  topics:
    departmentstatus: teamj.department-status.0
    missionpreparation : teamj.mission-preparation.0
