spring:
  main:
    allow-bean-definition-overriding: true
  jmx:
    enabled: false
  application:
    name: Demo


server:
  port: 8030
grpc:
  enable-reflection: true
  port: 8031

api:
  telemetry:
    host: ${TELEMETRY_HOST:localhost}
    port: ${TELEMETRY_PORT:8090}
