spring:
  main:
    allow-bean-definition-overriding: true
  jmx:
    enabled: false
  application:
    name: Demo


server:
  port: 8030
grpc:
  enable-reflection: true
  port: 8031

api:
  telemetry:
    host: ${TELEMETRY_HOST:localhost}
    port: ${TELEMETRY_PORT:8090}
    
kafka:
  broker:
    host: ${KAFKA_BROKER_HOST:localhost}
    port: ${KAFKA_BROKER_PORT:19092}
  schema:
    host: ${SCHEMA_BROKER_HOST:http://localhost}
    port: ${SCHEMA_BROKER_PORT:9090}
    group:
      booster: blue-origin-booster