spring:
  main:
    allow-bean-definition-overriding: true
  jmx:
    enabled: false
  application:
    name: Demo
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: telemetry


server:
  port: 8094
