spring:
  main:
    allow-bean-definition-overriding: true
  jmx:
    enabled: false
  application:
    name: Demo

server:
  port: 8070

grpc:
  enable-reflection: true
  port: 8071

api:
  payload:
    host: ${PAYLOAD_HOST:localhost}
    port: ${PAYLOAD_PORT:8050}
  rocket:
    host: ${ROCKET_HOST:localhost}
    port: ${PAYLOAD_PORT:8080}
