package fr.unice.polytech.soa.team.j.bluegalacticx.rocket.entities;

public enum RocketLaunchStep {
    NOT_STARTED, PREPARATION, STARTUP, MAIN_ENGINE_START, LIFTOFF, ENTER_MAXQ, MAXQ_PASSED, MAIN_ENGINE_CUTOFF, STAGE_SEPARATION, SECOND_ENGINE_RUNNING, FAIRING_SEPARATION, SECOND_ENGINE_CUTOFF, PAYLOAD_SEPARATION, FINISHED
}
